// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMELwanK_6WCuphGIFB_ZCyOYzv7hE97A',
    appId: '1:18584699136:web:e55dbbeb1095c6729e73e5',
    messagingSenderId: '18584699136',
    projectId: 'meow-assistan',
    authDomain: 'meow-assistan.firebaseapp.com',
    storageBucket: 'meow-assistan.appspot.com',
    measurementId: 'G-4Y1F0RHDR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoUaQif5y759-dLTD4DvwTEGWGT2nyPEs',
    appId: '1:18584699136:android:a5ae1b719d85c3959e73e5',
    messagingSenderId: '18584699136',
    projectId: 'meow-assistan',
    storageBucket: 'meow-assistan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1I9TTV3JFhcEG8O15qg8HFIvmlIObmMo',
    appId: '1:18584699136:ios:ca3ccb779526fae49e73e5',
    messagingSenderId: '18584699136',
    projectId: 'meow-assistan',
    storageBucket: 'meow-assistan.appspot.com',
    iosClientId: '18584699136-eabtpirvkkegmho67pc1j16hpc387d25.apps.googleusercontent.com',
    iosBundleId: 'com.vqh2602.meowassistan',
  );
}
